version: "3.9"

services:
  frontend:
    build: .
    container_name: gmm_movie_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host